- README.md
```
[ ] Feature
[ ] Bugfix
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
-
N/A
> feat: add Diego Espino's info to the ReadMe

- README.md
```
[ ] Feature
[ ] Bugfix
[x] Documentation content changes
[ ] Tests
[ ] Other
```
- Added my name, LinkedIn, and picture
N/A
> GYM-12-Danny-Rivas Added my details to the README

- README.md
PR introduces updated README.md with my name, LinkedIn profile and public image 
```
[ ] Feature
[ ] Bugfix
[X] Documentation content changes
[ ] Tests
[ ] Other
```
[Jira Link](https://dallas-cohort.atlassian.net/browse/GYM-7)
What's new? name, LinkedIn profile and public image on README file
> updated README.md with LinkedIn profile link, image link and name

- README.md
```
[ ] Feature
[ ] Bugfix
[x] Documentation content changes
[ ] Tests
[ ] Other
```
- Updated my details in README.md file
N/A
> docs: updated README with my details (GYM-8)

- README.md
- app/page.tsx
```
[ ] Feature
[ ] Bugfix
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
-
N/A
> Gym 11 noah - added personal details to readme

- README.md
This PR introduces updated info for Joe Aguado in the ReadMe file
```
[ ] Feature
[ ] Bugfix
[x] Documentation content changes
[ ] Tests
[ ] Other
```
[Jira Link](https://dallas-cohort.atlassian.net/browse/GYM-9)
-
N/A
> feat: update readme info

- README.md
```
[ ] Feature
[ ] Bugfix
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
-
N/A
> chore: update README with personal details (GYM-15)

- app/globals.css
(GYM-36)
Set up color palate in globals.css
Updated only 'Primary' color and 'Muted' color for now to see how this impacts ShadCN styled components. Color palate can be updated accordingly as more components are built and we see what color arguments are being used.
> chore: update globals css primary styling (GYM-36)

- README.md
- app/api/classes/[classId]/route.ts
- app/api/classes/create/route.ts
- app/api/classes/delete/route.ts
- app/api/classes/getAll/route.ts
- app/api/classes/update/route.ts
- app/api/coaches/getAll/route.ts
- lib/zodSkema.ts
- package-lock.json
- package.json
Added validation to the admin classes endpoints using Zod.
Created getAll by date functionality.
ex. http://localhost:3000/api/classes/getAll?date=2025-08-06
Updated classes endpoints to reflect current tables.
[GYM-85]: https://dallas-cohort.atlassian.net/browse/GYM-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Gym 85 be add validation update documentation update endpoints to lowercase

- README.md
> add documentation for cafe endpoints

- app/api/cafe/items/edit/[productId]/route.ts
Added edit item endpoint
Endpoint: /api/cafe/items/edit/[productId]
Make sure to add JSON body to update item data
You do not have to include all fields, just the ones that need updating
[GYM-91]: https://dallas-cohort.atlassian.net/browse/GYM-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> added edit item endpoint

- README.md
- app/api/checkins/route.ts
- app/member/profile/page.tsx
- components/layouts/member/memberProfile.tsx
- constants/icons.ts
- constants/labels.ts
- types/shared.ts
- added endpoint to get all check-ins by user id 
- created member profile page 
[GYM-95]: https://dallas-cohort.atlassian.net/browse/GYM-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: member profile and /checkins to get checkins by id endpoint (GYM-95)

- app/member/profile/page.tsx
- removed notifications and invite friends from member profile UI
[GYM-98]: https://dallas-cohort.atlassian.net/browse/GYM-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: removing notifications and invite friends

- app/admin/class-schedules/page.tsx
- components/class-schedules/ClassCard.tsx
- components/class-schedules/CoachTypeSidebarSection.tsx
- components/class-schedules/modals/AddClassModal.tsx
- hooks/useClassSchedules.ts
- lib/zod/zodSkema.ts
- types/shared.ts
Updated Dialog Boxes and updated zod.
[GYM-99]: https://dallas-cohort.atlassian.net/browse/GYM-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Gym 99 update dialog boxes in admin classes

- README.md
- app/admin/dashboard/page.tsx
- app/api/cafe/items/topPurchases/route.ts
- components/admin/dashboard/TopCafePurchases.tsx
Added TopCafePurchases Component to the admin dashboard page.tsx + added the API route to get top 5 purchased products
[GYM-105]: https://dallas-cohort.atlassian.net/browse/GYM-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add TopCafePurchases component to admin dashboard (GYM-105)

- README.md
- app/admin/analytics/page.tsx
- app/member/profile/page.tsx
- components/admin/analytics/ActiveGymHoursCard.tsx
- components/admin/analytics/AnalyticsStatCard.tsx
- components/admin/analytics/ClassAttendanceCard.tsx
- components/admin/analytics/MembershipGrowthCard.tsx
- components/admin/analytics/TargetRevenueCard.tsx
- constants/icons.ts
- constants/labels.ts
- types/shared.ts
- created analytics dashboard for admin flow 
- generic stat card component 
- individual chart card components 
- updated labels, types, icons 
- https://recharts.org/en-US
- https://ui.shadcn.com/charts/area
[GYM-96]: https://dallas-cohort.atlassian.net/browse/GYM-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Gym 96 fe analytics dashboard

- app/admin/analytics/page.tsx
- components/admin/analytics/ActiveGymHoursCard.tsx
- components/admin/analytics/ClassAttendanceCard.tsx
- components/admin/analytics/MembershipGrowthCard.tsx
- components/admin/analytics/TargetRevenueCard.tsx
- constants/analyticsConstants.ts
- constants/mockData.ts
- added color to analytics page
- refactored constants to dedicated file 
[GYM-114]: https://dallas-cohort.atlassian.net/browse/GYM-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: adding analytics constants and colors

- README.md
- app/api/invoices/[userId]/route.ts
- app/api/invoices/add/route.ts
- lib/zod/invoiceSchema.ts
- add invoice to user_invoice table endpoint 
http://localhost:3000/api/invoices/add
{
"user_id": "e56f1b0b-cf47-42d2-8a82-ae833ed1a896",
"invoice_amount": 500.00
}
- get all invoices by user_id from user_invoice table endpoint 
http://localhost:3000/api/invoices/c160f12b-f5ea-4ceb-a8ed-36b1d14eb212
- zod validation file 
[GYM-115]: https://dallas-cohort.atlassian.net/browse/GYM-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: invoice endpoints (GYM-115)

- components/layouts/admin/site-header.tsx
[GYM-124]: https://dallas-cohort.atlassian.net/browse/GYM-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add proper pathname collecting for slug pages on admin dashboard

- components/layouts/member/moodPicker.tsx
> styling: make the moodPicker component a little more legible

- app/(preAuth)/layout.tsx
- components/layouts/auth/footer2.tsx
- constants/labels.ts
> feat: update footer with our repo and linkedIns

- app/api/gemini/initialMessage/route.ts
- app/api/gemini/route.ts
- app/member/dashboard/clientCheckinNotice.tsx
- app/member/dashboard/page.tsx
- components/layouts/member/ClassDetailsModal.tsx
- components/layouts/member/FloatingAIChat.tsx
- components/layouts/member/classes.tsx
- components/layouts/member/enrolled-classes-client.tsx
- components/layouts/member/moodAvatar.tsx
- components/layouts/member/moodPicker.tsx
- constants/geminiChatbot.ts
- constants/labels.ts
Moved and updated move selector to AI modal.
Updated checkin pop up to ask for current mood for the ai coach. This also updated DB with checkin.
Added realtime update of classes in dashboard when user enrolls from dashboard.
Fixed AI chatbot not recognizing the current mood (was passing in wrong userId) and updated prompt.
> Gym 131 move emoji to ai modal and update prompt

- README.md
- app/admin/members/[id]/page.tsx
- app/admin/members/page.tsx
- app/api/adminMemberProfile/[userId]/route.ts
- components/layouts/admin/app-sidebar.tsx
- admin member profile endpoint 
- synced to UI 
- updated app sidebar
[GYM-130]: https://dallas-cohort.atlassian.net/browse/GYM-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE - connect admin member to profile endpoint
